USE max76PRD
GO

SELECT MAX(ATTEMPTDATE) LASTLOGIN 
FROM dbo.LOGINTRACKING 
WHERE USERID = 'BRANNTR1' 
AND ATTEMPTRESULT = 'LOGIN' 
AND ATTEMPTDATE > DATEADD(DAY, -90, GETDATE())
GROUP BY logintrackingid
ORDER BY LOGINTRACKINGID DESC;