DECLARE @date DATETIME2 = GETDATE()
SELECT @date AS GETDATE
SELECT CURRENT_TIMESTAMP AS 'CURRENT_TIMESTAMP'
SELECT GETUTCDATE() AS GETUTCDATE
SELECT SYSDATETIME() AS SYSDATETIME
SELECT SYSUTCDATETIME() AS SYSUTCDATETIME
SELECT SYSDATETIMEOFFSET() AS SYSDATETIMEOFFSET
SELECT DATALENGTH(N'xyz') AS DATALENGTH
SELECT LEN('xyz  ') AS Length